import type { NextPage } from 'next'
import Head from 'next/head'
import { QueryClient, QueryClientProvider } from 'react-query'

const Home: NextPage = () => {

  const client = new QueryClient();

  return (
    <QueryClientProvider client={client}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <div>hej</div>

     

     

      </QueryClientProvider>
  )
}

export default Home
